// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBgeOmA6BWIXDsM1zzwK-pYZdjHpa18xBA',
    appId: '1:961632797049:web:d3d465e6d10bf81fad6fa8',
    messagingSenderId: '961632797049',
    projectId: 'imaipay',
    authDomain: 'imaipay.firebaseapp.com',
    storageBucket: 'imaipay.firebasestorage.app',
    measurementId: 'G-YMYQP97MCN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfr2b19n-m4uf4sTNfNwJUEFBGalDUIDw',
    appId: '1:961632797049:android:70b60d634317498aad6fa8',
    messagingSenderId: '961632797049',
    projectId: 'imaipay',
    storageBucket: 'imaipay.firebasestorage.app',
  );
}
